### ISSUE TITLE
0.4.x release with Python3 support

### ISSUE THREAD

**Issue by ejelome** [wearpants/twiggy#36]
I'm testing twiggy on an isolated environment with `Python3.4` using `virtualenvwrapper`, here's the scenario:

## Creating the isolated environment:
```
(twiggy) username@username-VirtualBox ~/Devel/twiggy 
$ mkproject -p /usr/bin/python3 twiggy
Running virtualenv with interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in twiggy/bin/python3
Also creating executable in twiggy/bin/python
Installing setuptools, pip...done.
Creating /home/username/Devel/twiggy
Setting project for twiggy to /home/username/Devel/twiggy
```

## Installing `twiggy`:
```
(twiggy) username@username-VirtualBox ~/Devel/twiggy 
$ pip install twiggy
Downloading/unpacking twiggy
  Downloading Twiggy-0.4.5.tar.gz (55kB): 55kB downloaded
  Running setup.py (path:/home/username/.virtualenvs/twiggy/build/twiggy/setup.py) egg_info for package twiggy
    
Installing collected packages: twiggy
  Running setup.py install for twiggy
    
Successfully installed twiggy
Cleaning up...
```

## Testing w/ Python3 interpreter:
It first complains about a missing module (`logger`).
```
(twiggy) username@username-VirtualBox ~/Devel/twiggy 
$ python
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import twiggy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/.virtualenvs/twiggy/lib/python3.4/site-packages/twiggy/__init__.py", line 6, in <module>
    import logger
ImportError: No module named 'logger'
>>> exit()
```

## Let's install that `logger`:
```
(twiggy) username@username-VirtualBox ~/Devel/twiggy 
$ pip install logger
Downloading/unpacking logger
  Downloading logger-1.4.tar.gz
  Running setup.py (path:/home/username/.virtualenvs/twiggy/build/logger/setup.py) egg_info for package logger
    
Installing collected packages: logger
  Running setup.py install for logger
    
Successfully installed logger
Cleaning up...
```

## Let's test it again:
This time, it will complain about a missing module: `filters`
```
(twiggy) username@username-VirtualBox ~/Devel/twiggy 
$ python
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> pip install twiggy
  File "<stdin>", line 1
    pip install twiggy
              ^
SyntaxError: invalid syntax
>>> import twiggy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/.virtualenvs/twiggy/lib/python3.4/site-packages/twiggy/__init__.py", line 7, in <module>
    import filters
ImportError: No module named 'filters'
>>> exit()
```

## Let's try to install that missing module:
```
(twiggy) username@username-VirtualBox ~/Devel/twiggy 
$ pip install filters
Downloading/unpacking filters
  Could not find any downloads that satisfy the requirement filters
Cleaning up...
No distributions at all found for filters
Storing debug log for failure in /home/username/.pip/pip.log
```

Now we're stuck :)

**Comment by wearpants** [comment]
yeah, will fix to be `from . import filters` or whatever

**Comment by wearpants** [comment]
Hmm, this is fixed on master but not maint-0.4. Le sigh, I should cut a new release from master (and properly clean it up)... ugh, old/bad mercurial history. :-(

**Comment by msabramo** [comment]
@wearpants:

Why does the `README.rst` say:

> Note that master is currently in flux and may be broken. Please use the maint-0.4 branch for stable 
> development/forks.

The tox and Travis CI tests are passing on master for all Python versions, including Python 3.

What aspects are broken in `master`?

**Comment by wearpants** [comment]
There's half done changes; specifically the log_compat module (which is a
shim to stdlib logging) - no docs  or tests... Maybe other features  as
well. These probably should all be in feature branches for a 0.5 release &
master can be used as 0.4.x releases. I'll try to sort this out early next
week

**Comment by msabramo** [comment]
Maybe it's not as bad as you remember? According to https://github.com/wearpants/twiggy/pull/44, `log_compat` has 98% test coverage. OTOH...

```
twiggy/features/__init__       2      2      0      0     0%   2-3
twiggy/features/procinfo       5      5      0      0     0%   3-14
twiggy/features/socket         9      9      0      0     0%   2-25
```

**Comment by msabramo** [comment]
See PR #49. This brings over changes from PR #34, which targeted the `master` branch and applies them to the `maint-0.4` branch.

In case it's easier to put out a new release from the `maint-0.4` branch rather than the `master` branch (which you've said is in an indeterminate state) -- to make Python 3.

**Comment by wearpants** [comment]
Features were deprecated b/c they needed a rewrite. log_compat needs some
structural cleanup too. The log_compat test coverage doesn't quite capture
what needs to be tested - ideally, log_compat should be able to pass the
relevant portions of the stdlib's test suite for logging.

On Fri, Jan 16, 2015 at 10:03 AM, Marc Abramowitz <notifications@github.com>
wrote:

> Maybe it's not as bad as you remember? According to #44
> <https://github.com/wearpants/twiggy/pull/44>, log_compat has 98% test
> coverage. OTOH...
>
> twiggy/features/__init__       2      2      0      0     0%   2-3
> twiggy/features/procinfo       5      5      0      0     0%   3-14
> twiggy/features/socket         9      9      0      0     0%   2-25
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wearpants/twiggy/issues/36#issuecomment-70265489>.
>



-- 
Peter Fein | wearpants.org | @wearpants

I read email at the start and end of each day. IM if urgent.

**Comment by wearpants** [comment]
see also #49 #34 #26.

**Comment by touilleMan** [comment]
Hi,

Any idea when the Python3 version of twiggy will be available on pypi ?
I'm working on a Python3 version of diesel (http://diesel.io/), it seems to be the last reluctant dependency...

Thanks ;-)

**Comment by wearpants** [comment]
I will try to cut this in the next few days

**Comment by wearpants** [comment]
Pushed, finally! Thanks to @msabramo <3 <3 <3

**Comment by msabramo** [comment]
Awesome!

Though we should add the Python 3 classifier to `setup.py` - see https://github.com/wearpants/twiggy/pull/52
