### ISSUE TITLE
camelCase

### ISSUE THREAD

**Issue by Riamse** [wearpants/twiggy#53]
This library uses way too much of it, especially in the method names. I propose creating under_score aliases, similar to what was vaguely discussed at https://github.com/gawel/pyquery/pull/57 .

**Comment by wearpants** [comment]
Which names did you have in mind? Pretty sure this was fixed quite some time ago. All existing `camelCase` names should already have been converted to `under_score` style, and the camelCase variants raise `DeprecationWarning`.

**Comment by Riamse** [comment]
True. I was misled by the docs.
False alarm, please disregard.
